name: weather_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  retrofit: ">=4.0.0 <5.0.0"
  logger: any #for logging purpose
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  modal_bottom_sheet: ^2.1.2
  geolocator: ^10.1.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  intl: ^0.18.1
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #  required dart >=2.19
  retrofit_generator: ">=7.0.0 <8.0.0"
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/
  generate: true

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
